# Site settings
title: The Daily Viz
email: mattstiles@gmail.com
description: >-
  A (retired) digital sketchpad for data stories, by Matt Stiles.
baseurl: ""
url: "https://thedailyviz.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - data/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Author
author:
  name: Matt Stiles
  email: mattstiles@gmail.com

# Google Analytics
google_analytics:
  tracking_id: "G-EFP5W9BBBD"
  stream_id: "5250781266"

# Google AdSense
google_adsense:
  client_id: "ca-pub-8839053265498229" 